name: Commit check

run-name: Commitlint

on: 
  push: 
  workflow_call:
  tags-ignore:
    - 'v[0-9]+'
    
jobs:
  Validation-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Commit lint
        uses: wagoid/commitlint-github-action@v5
