name: Deploy

run-name: Deploy

on: workflow_dispatch  

jobs:
  Deploy-proj:
    permissions: 
      issues: write
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get latest tag
        run: |
          latest_tag=$(basename ${{ github.ref_name }})
          echo "TAG=$latest_tag" >> $GITHUB_ENV
          echo "Tag: $latest_tag"
      - name: Build
        run: npm ci && npm run build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
      - uses: lee-dohm/close-matching-issues@v2
        with:
          query: ${{ env.TAG }}
          token: ${{ secrets.GITHUB_TOKEN }}

    # steps:   
    #   - name: Checkout
    #     uses: actions/checkout@v3
    #   - name: npm install
    #     run: npm ci
    #   - name: build
    #     run: npm run build
    #   - name: Get current branch name


    #   - name: Deploy to GitHub Pages
    #     uses: peaceiris/actions-gh-pages@v3
    #     with:
    #       github_token: ${{ secrets.GITHUB_TOKEN }}
    #       publish_dir: ./build
        # uses: crazy-max/ghaction-github-pages@v3
        # with:
        #   target_branch: gh-pages
        #   build_dir: build
        # env:
        #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # - name: Get latest tag
      #   run: |
      #     latest_tag=$(git describe --abbrev=0 --tags)
      #     echo "TAG=$latest_tag" >> $GITHUB_ENV 
          #     run: |
          # branch_name=$(basename ${{ github.ref }})
          # echo "branch=$branch_name" >> $GITHUB_ENV 
          # echo "Current branch name: $branch_name"