name: Deploy

run-name: Deploy

on: workflow_dispatch

jobs:
  Deploy-proj:
    runs-on: ubuntu-latest
    steps:
      - name: Get latest tag
        run: |
          latest_tag=$(git describe --abbrev=0 --tags)
          echo "TAG=$latest_tag" >> $GITHUB_ENV    
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ env.TAG }}
      - name: Setup Node JS
        uses: actions/setup-node@v3
        with:
          node-version: v16.19.0
          cache: npm
      - name: npm install
        run: npm ci
      - name: build
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: ${{ env.TAG }}
          build_dir: build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
