name: Create release

on:
  push:
    tags:
      - 'v[0-9]+'
  workflow_dispatch:

permissions:
  contents: write
  issues: write

jobs:
  Testing:
    uses: ./.github/workflows/pr-test.yml

  create_branch:
    needs: [Testing]
    runs-on: ubuntu-latest
    # steps:
    #   - name: Checkout repository
    #     uses: actions/checkout@v3
    #     with:
    #       token: ${{ secrets.GH_ACTIONS }}
    #   - name: Create branch
    #     run: |
    #       BRANCH_NAME=release-${{ github.ref_name }}
    #       git checkout -b $BRANCH_NAME
    #       git push -u origin $BRANCH_NAME --tags
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3


      - name: Create branch
        run: |
          BRANCH_NAME=release-${{ github.ref_name }}
          git checkout -b $BRANCH_NAME
          git push -u origin $BRANCH_NAME

  issue-rel:
    needs: [create_branch]
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - uses: nashmaniac/create-issue-action@v1.2
        name: Create Issue Action
        with:
          title: Build Failed
          token: ${{secrets.GITHUB_TOKEN}}
          assignees: ${{github.actor}}
          labels: worflow-failed
          body: Workflow failed for commit ${{github.sha}}