name: Create release

on:
  push:
    tags:
      - 'v[0-9]+'
  workflow_dispatch:

permissions:
  contents: write
  issues: write

jobs:
  Testing:
    uses: ./.github/workflows/pr-test.yml

  create_branch:
    needs: [Testing]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create branch
        run: |
          BRANCH_NAME=release-${{ github.ref_name }}
          git checkout -b $BRANCH_NAME
          git push -u origin $BRANCH_NAME

  issue-rel:
    needs: [create_branch]
    name: Create Release
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get preTag
        shell: bash
        id: previous-tag
        run: echo "::set-output name=previous-tag::$(git describe --abbrev=0 --tags $(git rev-list --tags --skip=1 --max-count=1))"

      - name: Build Changelog
        uses: nielstenboom/semantic-changelog-generator@v1.2.0
        id: changelog
        with:
          base: ${{ steps.previous-tag.outputs.previous-tag }}
          head: ${{ github.ref_name }}

      # - name: Create Issue Action
      #   id: create-issue
      #   uses: nashmaniac/create-issue-action@v1.2
      #   with:
      #     title: Release ${{ github.ref_name }}
      #     token: ${{secrets.GITHUB_TOKEN}}
      #     assignees: ${{github.actor}}
      #     labels: New version
      #     body: |
      #       Автор релиза: ${{github.actor}}

      #       Дата релиза: ${{ github.event.head_commit.timestamp }}

      #       Версия: ${{ github.ref_name }}
            
      #       Changelog:

      #       ${{ steps.changelog.outputs.changelog }}

      - name: Create Issue Action
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AUTHOR: ${{github.actor}}
          DATE: ${{ github.event.head_commit.timestamp }}
          VERSION: ${{ github.ref_name }}
          CHANGELOG: ${{ steps.changelog.outputs.changelog }}
        with:
          update_existing: true
          search_existing: all