name: Testing

run-name: Testing

on: [push, pull_request, workflow_call]

jobs:
  Start-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node JS
        uses: actions/setup-node@v3
        with:
          node-version: v16.19.0
          cache: npm
      - name: npm install
        run: npm ci
      - name: Check lint
        run: npm run lint
      - name: Unit test
        run: npm run test-ci
      